### ISSUE TITLE
setting `cmap` for multiscale image leads to error 

### ISSUE THREAD

**Issue by LucaMarconato** [scverse/spatialdata-plot#360]
```python
from spatialdata.datasets import blobs
import spatialdata_plot

sdata = blobs()
sdata.pl.render_images('blobs_multiscale_image', cmap='gray')
```

gives
```
Traceback (most recent call last):
  File "/opt/miniconda3/envs/ome39/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3550, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-97fd56a4e55c>", line 5, in <module>
    sdata.pl.render_images('blobs_multiscale_image', cmap='gray')
  File "/Users/macbook/embl/projects/basel/spatialdata/src/spatialdata/_utils.py", line 261, in wrapper
    return f(*args, **kwargs)
  File "/Users/macbook/embl/projects/basel/spatialdata-plot/src/spatialdata_plot/pl/basic.py", line 476, in render_images
    params_dict = _validate_image_render_params(
  File "/Users/macbook/embl/projects/basel/spatialdata-plot/src/spatialdata_plot/pl/utils.py", line 1909, in _validate_image_render_params
    cmap_length = len(channel) if channel is not None else len(spatial_element.c)
  File "/opt/miniconda3/envs/ome39/lib/python3.9/site-packages/datatree/common.py", line 54, in __getattr__
    raise AttributeError(
AttributeError: 'DataTree' object has no attribute 'c'
```

**Comment by timtreis** [comment]
https://github.com/scverse/spatialdata-plot/issues/354 duplicate
